/**
 * Official Competitive Exam Sources Directory
 * All links point directly to official government bodies.
 * No third-party scrapers or blogs.
 */

export const EXAM_SOURCES = [
  // ==========================================
  // 1. Central / National Level Sources
  // ==========================================
  {
    organization: "UPSC",
    state: "All India",
    category: "Central Government",
    url: "https://upsc.gov.in",
    calendarUrl: "https://upsc.gov.in/examinations/exam-calendar",
    scraperType: "html",
    scraperAdapter: "upsc",
    enabled: true,
  },
  {
    organization: "SSC",
    state: "All India",
    category: "Central Government",
    url: "https://ssc.gov.in",
    calendarUrl: "https://ssc.gov.in/candidate-portal/annual-calendar",
    scraperType: "html",
    scraperAdapter: "ssc",
    enabled: true,
  },
  {
    organization: "NTA",
    state: "All India",
    category: "Entrance & Eligibility",
    url: "https://nta.ac.in",
    calendarUrl: "https://nta.ac.in",
    scraperType: "html",
    scraperAdapter: "nta",
    enabled: true,
  },
  {
    organization: "IBPS",
    state: "All India",
    category: "Banking",
    url: "https://www.ibps.in",
    calendarUrl: "https://www.ibps.in",
    scraperType: "html",
    scraperAdapter: "ibps",
    enabled: true,
  },
  {
    organization: "SBI",
    state: "All India",
    category: "Banking",
    url: "https://sbi.co.in/web/careers",
    calendarUrl: "https://sbi.co.in/web/careers/current-openings",
    scraperType: "html",
    scraperAdapter: "sbi",
    enabled: true,
  },
  {
    organization: "RRB",
    state: "All India",
    category: "Railway",
    url: "https://indianrailways.gov.in",
    calendarUrl: "https://rrbcdg.gov.in",
    scraperType: "html",
    scraperAdapter: "railway",
    enabled: true,
  },
  {
    organization: "AFCAT",
    state: "All India",
    category: "Defence",
    url: "https://afcat.cdac.in/AFCAT/",
    calendarUrl: "https://afcat.cdac.in/AFCAT/",
    scraperType: "html",
    scraperAdapter: "afcat",
    enabled: true,
  },
  {
    organization: "Indian Coast Guard",
    state: "All India",
    category: "Defence",
    url: "https://joinindiancoastguard.cdac.in",
    calendarUrl: "https://joinindiancoastguard.cdac.in",
    scraperType: "html",
    scraperAdapter: "coastguard",
    enabled: true,
  },

  // ==========================================
  // 2. State Public Service Commissions (PSCs)
  // ==========================================
  {
    organization: "TNPSC",
    state: "Tamil Nadu",
    category: "State Government",
    url: "https://www.tnpsc.gov.in",
    calendarUrl: "https://www.tnpsc.gov.in/English/annual_planner.html",
    scraperType: "html",
    scraperAdapter: "tnpsc",
    enabled: true,
  },
  {
    organization: "Kerala PSC",
    state: "Kerala",
    category: "State Government",
    url: "https://www.keralapsc.gov.in",
    calendarUrl: "https://www.keralapsc.gov.in/examination-programme-calendar",
    scraperType: "html",
    scraperAdapter: "kerala_psc",
    enabled: true,
  },
  {
    organization: "APPSC",
    state: "Andhra Pradesh",
    category: "State Government",
    url: "https://psc.ap.gov.in",
    calendarUrl: "https://portal-psc.ap.gov.in/HomePages/ExaminationCalendar",
    scraperType: "html",
    scraperAdapter: "appsc",
    enabled: true,
  },
  {
    organization: "TGPSC",
    state: "Telangana",
    category: "State Government",
    url: "https://www.tspsc.gov.in",
    calendarUrl: "https://websnew.tspsc.gov.in",
    scraperType: "html",
    scraperAdapter: "tgpsc",
    enabled: true,
  },
  {
    organization: "KPSC Karnataka",
    state: "Karnataka",
    category: "State Government",
    url: "https://kpsc.kar.nic.in",
    calendarUrl: "https://kpsc.kar.nic.in",
    scraperType: "html",
    scraperAdapter: "kpsc",
    enabled: true,
  },
  {
    organization: "MPSC Maharashtra",
    state: "Maharashtra",
    category: "State Government",
    url: "https://mpsc.gov.in",
    calendarUrl: "https://mpsc.gov.in/timetable",
    scraperType: "html",
    scraperAdapter: "mpsc",
    enabled: true,
  },
  {
    organization: "GPSC Gujarat",
    state: "Gujarat",
    category: "State Government",
    url: "https://gpsc.gujarat.gov.in",
    calendarUrl: "https://gpsc.gujarat.gov.in",
    scraperType: "html",
    scraperAdapter: "gpsc",
    enabled: true,
  },
  {
    organization: "RPSC Rajasthan",
    state: "Rajasthan",
    category: "State Government",
    url: "https://rpsc.rajasthan.gov.in",
    calendarUrl: "https://rpsc.rajasthan.gov.in/examdashboard",
    scraperType: "html",
    scraperAdapter: "rpsc",
    enabled: true,
  },
  {
    organization: "UPPSC",
    state: "Uttar Pradesh",
    category: "State Government",
    url: "https://uppsc.up.nic.in",
    calendarUrl: "https://uppsc.up.nic.in",
    scraperType: "html",
    scraperAdapter: "uppsc",
    enabled: true,
  },
  {
    organization: "BPSC",
    state: "Bihar",
    category: "State Government",
    url: "https://www.bpsc.bih.nic.in",
    calendarUrl: "https://www.bpsc.bih.nic.in",
    scraperType: "html",
    scraperAdapter: "bpsc",
    enabled: true,
  },
  {
    organization: "MPPSC",
    state: "Madhya Pradesh",
    category: "State Government",
    url: "https://mppsc.mp.gov.in",
    calendarUrl: "https://mppsc.mp.gov.in",
    scraperType: "html",
    scraperAdapter: "mppsc",
    enabled: true,
  },
  {
    organization: "WBPSC",
    state: "West Bengal",
    category: "State Government",
    url: "https://psc.wb.gov.in",
    calendarUrl: "https://psc.wb.gov.in",
    scraperType: "html",
    scraperAdapter: "wbpsc",
    enabled: true,
  },
  {
    organization: "OPSC",
    state: "Odisha",
    category: "State Government",
    url: "https://www.opsc.gov.in",
    calendarUrl: "https://www.opsc.gov.in",
    scraperType: "html",
    scraperAdapter: "opsc",
    enabled: true,
  },
  {
    organization: "PPSC Punjab",
    state: "Punjab",
    category: "State Government",
    url: "https://ppsc.gov.in",
    calendarUrl: "https://ppsc.gov.in",
    scraperType: "html",
    scraperAdapter: "ppsc",
    enabled: true,
  },
  {
    organization: "HPSC",
    state: "Haryana",
    category: "State Government",
    url: "https://hpsc.gov.in",
    calendarUrl: "https://hpsc.gov.in",
    scraperType: "html",
    scraperAdapter: "hpsc",
    enabled: true,
  },
  {
    organization: "HPPSC",
    state: "Himachal Pradesh",
    category: "State Government",
    url: "http://www.hppsc.hp.gov.in",
    calendarUrl: "http://www.hppsc.hp.gov.in",
    scraperType: "html",
    scraperAdapter: "hppsc",
    enabled: true,
  },
  {
    organization: "UKPSC",
    state: "Uttarakhand",
    category: "State Government",
    url: "https://psc.uk.gov.in",
    calendarUrl: "https://psc.uk.gov.in",
    scraperType: "html",
    scraperAdapter: "ukpsc",
    enabled: true,
  },
  {
    organization: "JPSC",
    state: "Jharkhand",
    category: "State Government",
    url: "https://www.jpsc.gov.in",
    calendarUrl: "https://www.jpsc.gov.in",
    scraperType: "html",
    scraperAdapter: "jpsc",
    enabled: true,
  },
  {
    organization: "CGPSC",
    state: "Chhattisgarh",
    category: "State Government",
    url: "https://psc.cg.gov.in",
    calendarUrl: "https://psc.cg.gov.in",
    scraperType: "html",
    scraperAdapter: "cgpsc",
    enabled: true,
  },
  {
    organization: "Goa PSC",
    state: "Goa",
    category: "State Government",
    url: "https://gpsc.goa.gov.in",
    calendarUrl: "https://gpsc.goa.gov.in",
    scraperType: "html",
    scraperAdapter: "goapsc",
    enabled: true,
  },
  {
    organization: "APSC Assam",
    state: "Assam",
    category: "State Government",
    url: "https://apsc.nic.in",
    calendarUrl: "https://apsc.nic.in",
    scraperType: "html",
    scraperAdapter: "apsc_assam",
    enabled: true,
  },
  {
    organization: "Manipur PSC",
    state: "Manipur",
    category: "State Government",
    url: "https://mpscmanipur.gov.in",
    calendarUrl: "https://mpscmanipur.gov.in",
    scraperType: "html",
    scraperAdapter: "manipur_psc",
    enabled: true,
  },
  {
    organization: "Meghalaya PSC",
    state: "Meghalaya",
    category: "State Government",
    url: "https://mpsc.nic.in",
    calendarUrl: "https://mpsc.nic.in",
    scraperType: "html",
    scraperAdapter: "meghalaya_psc",
    enabled: true,
  },
  {
    organization: "Mizoram PSC",
    state: "Mizoram",
    category: "State Government",
    url: "https://mpsc.mizoram.gov.in",
    calendarUrl: "https://mpsc.mizoram.gov.in",
    scraperType: "html",
    scraperAdapter: "mizoram_psc",
    enabled: true,
  },
  {
    organization: "NPSC Nagaland",
    state: "Nagaland",
    category: "State Government",
    url: "https://npsc.nagaland.gov.in",
    calendarUrl: "https://npsc.nagaland.gov.in",
    scraperType: "html",
    scraperAdapter: "npsc_nagaland",
    enabled: true,
  },
  {
    organization: "SPSC Sikkim",
    state: "Sikkim",
    category: "State Government",
    url: "https://spsc.sikkim.gov.in",
    calendarUrl: "https://spsc.sikkim.gov.in",
    scraperType: "html",
    scraperAdapter: "spsc_sikkim",
    enabled: true,
  },
  {
    organization: "TPSC Tripura",
    state: "Tripura",
    category: "State Government",
    url: "https://tpsc.tripura.gov.in",
    calendarUrl: "https://tpsc.tripura.gov.in",
    scraperType: "html",
    scraperAdapter: "tpsc_tripura",
    enabled: true,
  },
  {
    organization: "Arunachal Pradesh PSC",
    state: "Arunachal Pradesh",
    category: "State Government",
    url: "https://appsc.gov.in",
    calendarUrl: "https://appsc.gov.in",
    scraperType: "html",
    scraperAdapter: "arunachal_psc",
    enabled: true,
  },
  {
    organization: "JKPSC",
    state: "Jammu and Kashmir",
    category: "State Government",
    url: "http://jkpsc.nic.in",
    calendarUrl: "http://jkpsc.nic.in",
    scraperType: "html",
    scraperAdapter: "jkpsc",
    enabled: true,
  },
];
