import { Source } from './models.js';

export const INDIA = 'India';
export const GLOBAL = 'International';

export const SOURCES = [
  new Source({
    key: 'pib',
    name: 'Press Information Bureau',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Government & Public Policy',
    url: 'https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=1',
    allowed_domains: ['pib.gov.in', 'static.pib.gov.in'],
    mode: 'rss',
    priority: 10,
  }),
  new Source({
    key: 'egazette',
    name: 'eGazette of India',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Legislation & Rules',
    url: 'https://egazette.gov.in/',
    allowed_domains: ['egazette.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'sansad',
    name: 'Parliament of India',
    organisation: 'Parliament of India',
    region: INDIA,
    subject: 'Parliament & Legislation',
    url: 'https://sansad.in/',
    allowed_domains: ['sansad.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'sci_landmark',
    name: 'Supreme Court Landmark Judgment Summaries',
    organisation: 'Supreme Court of India',
    region: INDIA,
    subject: 'Constitution & Judiciary',
    url: 'https://www.sci.gov.in/landmark-judgment-summaries/',
    allowed_domains: ['sci.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'eci',
    name: 'Election Commission of India',
    organisation: 'Election Commission of India',
    region: INDIA,
    subject: 'Elections & Polity',
    url: 'https://www.eci.gov.in/media-publication',
    allowed_domains: ['eci.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'rbi',
    name: 'Reserve Bank of India',
    organisation: 'Reserve Bank of India',
    region: INDIA,
    subject: 'Banking & Economy',
    url: 'https://www.rbi.org.in/Scripts/rss.aspx',
    allowed_domains: ['rbi.org.in'],
    mode: 'rss_index',
    priority: 10,
  }),
  new Source({
    key: 'sebi',
    name: 'SEBI',
    organisation: 'Securities and Exchange Board of India',
    region: INDIA,
    subject: 'Capital Markets',
    url: 'https://www.sebi.gov.in/sebirss.xml',
    allowed_domains: ['sebi.gov.in'],
    mode: 'rss',
    priority: 10,
  }),
  /*
  new Source({
    key: 'finmin',
    name: 'Ministry of Finance',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Economy & Public Finance',
    url: 'https://finmin.gov.in/',
    allowed_domains: ['finmin.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  */
  new Source({
    key: 'budget',
    name: 'Union Budget',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Budget & Economy',
    url: 'https://www.indiabudget.gov.in/',
    allowed_domains: ['indiabudget.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'mospi',
    name: 'Ministry of Statistics and Programme Implementation',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Statistics & Economy',
    url: 'https://www.mospi.gov.in/',
    allowed_domains: ['mospi.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'niti',
    name: 'NITI Aayog',
    organisation: 'NITI Aayog',
    region: INDIA,
    subject: 'Policy & Development',
    url: 'https://www.niti.gov.in/',
    allowed_domains: ['niti.gov.in'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'cag',
    name: 'Comptroller and Auditor General of India',
    organisation: 'CAG of India',
    region: INDIA,
    subject: 'Governance & Public Finance',
    url: 'https://cag.gov.in/',
    allowed_domains: ['cag.gov.in'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'mea',
    name: 'Ministry of External Affairs',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'International Relations',
    url: 'https://www.mea.gov.in/',
    allowed_domains: ['mea.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'isro',
    name: 'ISRO',
    organisation: 'Indian Space Research Organisation',
    region: INDIA,
    subject: 'Science & Technology',
    url: 'https://www.isro.gov.in/',
    allowed_domains: ['isro.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'drdo',
    name: 'DRDO',
    organisation: 'Defence Research and Development Organisation',
    region: INDIA,
    subject: 'Defence & Technology',
    url: 'https://www.drdo.gov.in/',
    allowed_domains: ['drdo.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'mha',
    name: 'Ministry of Home Affairs',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Internal Security',
    url: 'https://www.mha.gov.in/',
    allowed_domains: ['mha.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'moefcc',
    name: 'Ministry of Environment, Forest and Climate Change',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Environment',
    url: 'https://moef.gov.in/',
    allowed_domains: ['moef.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'agri',
    name: 'Ministry of Agriculture and Farmers Welfare',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Agriculture',
    url: 'https://agriwelfare.gov.in/',
    allowed_domains: ['agriwelfare.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'mohfw',
    name: 'Ministry of Health and Family Welfare',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Health',
    url: 'https://mohfw.gov.in/',
    allowed_domains: ['mohfw.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'who',
    name: 'World Health Organization',
    organisation: 'WHO',
    region: GLOBAL,
    subject: 'Global Health',
    url: 'https://www.who.int/news-room/',
    allowed_domains: ['who.int'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'wto',
    name: 'World Trade Organization',
    organisation: 'WTO',
    region: GLOBAL,
    subject: 'International Trade',
    url: 'https://www.wto.org/library/rss/latest_news_e.xml',
    allowed_domains: ['wto.org'],
    mode: 'rss',
    priority: 10,
  }),
  /*
  new Source({
    key: 'imf',
    name: 'International Monetary Fund',
    organisation: 'IMF',
    region: GLOBAL,
    subject: 'Global Economy',
    url: 'https://www.imf.org/en/News',
    allowed_domains: ['imf.org'],
    mode: 'html',
    priority: 10,
  }),
  */
  new Source({
    key: 'worldbank',
    name: 'World Bank',
    organisation: 'World Bank',
    region: GLOBAL,
    subject: 'Development & Economy',
    url: 'https://www.worldbank.org/en/news',
    allowed_domains: ['worldbank.org'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'unfccc',
    name: 'UN Climate Change',
    organisation: 'UNFCCC',
    region: GLOBAL,
    subject: 'Climate Change',
    url: 'https://unfccc.int/news',
    allowed_domains: ['unfccc.int'],
    mode: 'html',
    priority: 10,
  }),
  /*
  new Source({
    key: 'unep',
    name: 'UN Environment Programme',
    organisation: 'UNEP',
    region: GLOBAL,
    subject: 'Environment',
    url: 'https://www.unep.org/news-and-stories',
    allowed_domains: ['unep.org'],
    mode: 'html',
    priority: 9,
  }),
  */
  new Source({
    key: 'unesco',
    name: 'UNESCO',
    organisation: 'UNESCO',
    region: GLOBAL,
    subject: 'Culture & Education',
    url: 'https://www.unesco.org/en/newsroom',
    allowed_domains: ['unesco.org'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'fao',
    name: 'Food and Agriculture Organization',
    organisation: 'FAO',
    region: GLOBAL,
    subject: 'Agriculture & Food Security',
    url: 'https://www.fao.org/newsroom/en',
    allowed_domains: ['fao.org'],
    mode: 'html',
    priority: 9,
  }),
  /*
  new Source({
    key: 'iaea',
    name: 'International Atomic Energy Agency',
    organisation: 'IAEA',
    region: GLOBAL,
    subject: 'Nuclear Science',
    url: 'https://www.iaea.org/newscenter',
    allowed_domains: ['iaea.org'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'fatf',
    name: 'Financial Action Task Force',
    organisation: 'FATF',
    region: GLOBAL,
    subject: 'Financial Integrity & Security',
    url: 'https://www.fatf-gafi.org/',
    allowed_domains: ['fatf-gafi.org'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'yojana',
    name: 'Yojana Magazine',
    organisation: 'Publications Division, Government of India',
    region: INDIA,
    subject: 'Socio-Economic Development',
    url: 'https://yojana.gov.in/',
    allowed_domains: ['yojana.gov.in', 'publicationsdivision.nic.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'kurukshetra',
    name: 'Kurukshetra Magazine',
    organisation: 'Publications Division, Government of India',
    region: INDIA,
    subject: 'Rural Development & Agriculture',
    url: 'https://yojana.gov.in/',
    allowed_domains: ['yojana.gov.in', 'publicationsdivision.nic.in'],
    mode: 'html',
    priority: 10,
  }),
  */
  new Source({
    key: 'thehindu',
    name: 'The Hindu',
    organisation: 'THG Publishing Private Limited',
    region: INDIA,
    subject: 'National & Polity News',
    url: 'https://www.thehindu.com/news/feeder/default.rss',
    allowed_domains: ['thehindu.com'],
    mode: 'rss',
    priority: 9,
  }),
  new Source({
    key: 'indianexpress',
    name: 'The Indian Express',
    organisation: 'Indian Express Group',
    region: INDIA,
    subject: 'National & Editorial News',
    url: 'https://indianexpress.com/section/india/feed/',
    allowed_domains: ['indianexpress.com'],
    mode: 'rss',
    priority: 9,
  }),
  new Source({
    key: 'economictimes',
    name: 'The Economic Times',
    organisation: 'Times Group',
    region: INDIA,
    subject: 'Economy & Business News',
    url: 'https://economictimes.indiatimes.com/news/economy/rssfeeds/1373380680.cms',
    allowed_domains: ['economictimes.indiatimes.com', 'indiatimes.com'],
    mode: 'rss',
    priority: 9,
  }),
  /*
  new Source({
    key: 'economist',
    name: 'The Economist',
    organisation: 'The Economist Group',
    region: GLOBAL,
    subject: 'Global Politics & Economics',
    url: 'https://www.economist.com/finance-and-economics/rss.xml',
    allowed_domains: ['economist.com'],
    mode: 'rss',
    priority: 9,
  }),
  */
  new Source({
    key: 'bbc',
    name: 'BBC News',
    organisation: 'BBC',
    region: GLOBAL,
    subject: 'World News',
    url: 'http://feeds.bbci.co.uk/news/world/rss.xml',
    allowed_domains: ['bbc.co.uk', 'bbc.com'],
    mode: 'rss',
    priority: 9,
  }),
  new Source({
    key: 'ft',
    name: 'Financial Times',
    organisation: 'The Financial Times Ltd',
    region: GLOBAL,
    subject: 'Global Finance & Markets',
    url: 'https://www.ft.com/world?format=rss',
    allowed_domains: ['ft.com'],
    mode: 'rss',
    priority: 9,
  }),
  new Source({
    key: 'employment_news',
    name: 'Employment News (Rozgar Samachar)',
    organisation: 'Publications Division, Government of India',
    region: INDIA,
    subject: 'Career & Schemes',
    url: 'https://employmentnews.gov.in/',
    allowed_domains: ['employmentnews.gov.in'],
    mode: 'html',
    priority: 10,
  }),
  new Source({
    key: 'epw',
    name: 'Economic and Political Weekly',
    organisation: 'Sameeksha Trust',
    region: INDIA,
    subject: 'Academic Research & Policy Analysis',
    url: 'https://www.epw.in/',
    allowed_domains: ['epw.in'],
    mode: 'html',
    priority: 10,
  }),
  /*
  new Source({
    key: 'down_to_earth',
    name: 'Down To Earth',
    organisation: 'Society for Environmental Communications',
    region: INDIA,
    subject: 'Environment & Development',
    url: 'https://www.downtoearth.org.in/rss',
    allowed_domains: ['downtoearth.org.in'],
    mode: 'rss',
    priority: 9,
  }),
  new Source({
    key: 'science_reporter',
    name: 'Science Reporter',
    organisation: 'CSIR-NISCPR',
    region: INDIA,
    subject: 'Science & Technology',
    url: 'https://www.niscpr.res.in/periodicals/science-reporter',
    allowed_domains: ['niscpr.res.in', 'res.in'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'un_news',
    name: 'UN News Portal',
    organisation: 'United Nations',
    region: GLOBAL,
    subject: 'Global Affairs & Peace',
    url: 'https://news.un.org/feed/view/en/story/xml',
    allowed_domains: ['un.org', 'news.un.org'],
    mode: 'rss',
    priority: 10,
  }),
  new Source({
    key: 'wef',
    name: 'World Economic Forum Agenda',
    organisation: 'WEF',
    region: GLOBAL,
    subject: 'Global Economy & Agenda',
    url: 'https://www.weforum.org/agenda/feed',
    allowed_domains: ['weforum.org'],
    mode: 'rss',
    priority: 9,
  }),
  new Source({
    key: 'sipri',
    name: 'SIPRI Research updates',
    organisation: 'Stockholm International Peace Research Institute',
    region: GLOBAL,
    subject: 'Defence & Arms Control',
    url: 'https://www.sipri.org/rss.xml',
    allowed_domains: ['sipri.org'],
    mode: 'rss',
    priority: 10,
  }),
  */
  new Source({
    key: 'education',
    name: 'Ministry of Education',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Education Policies & Schemes',
    url: 'https://www.education.gov.in/',
    allowed_domains: ['education.gov.in'],
    mode: 'html',
    priority: 9,
  }),
  new Source({
    key: 'ndma',
    name: 'National Disaster Management Authority',
    organisation: 'Government of India',
    region: INDIA,
    subject: 'Disaster Management Guidelines',
    url: 'https://ndma.gov.in/',
    allowed_domains: ['ndma.gov.in'],
    mode: 'html',
    priority: 9,
  }),
  /*
  new Source({
    key: 'sansad_tv',
    name: 'Sansad TV Publications',
    organisation: 'Parliament of India',
    region: INDIA,
    subject: 'Parliament Debates & Insights',
    url: 'https://sansadtv.gov.in/',
    allowed_domains: ['sansadtv.gov.in'],
    mode: 'html',
    priority: 9,
  }),
  */
];
